<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FichaSeguimientoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('ficha_seguimientos')->insert([
            [
                'fecha'            => '2024-05-08',
                'evaluador'        => 'María González Pizarro',
                'contexto'         => 'Recreo no estructurado',
                'emocion'          => 'Ansiedad elevada',
                'fisica'           => 'Tensión muscular, movimientos repetitivos',
                'conductales'      => 'Aislamiento de pares',
                'duracion'         => '25 minutos',
                'inteversion'      => 'Acompañamiento y técnica de respiración 4-7-8',
                'estrategia'       => 'Espacio de calma con audífonos de atenuación',
                'ayuda'            => 'Asistente de aula',
                'ayuda_externa'    => null,
                'corto_plaza'      => 'Incrementar tiempo en espacio seguro',
                'largo_plazo'      => 'Desarrollar autonomía en autorregulación',
                'seguimiento_fecha'=> '2024-06-08',
                'responsable'      => 'María González Pizarro',
                'seguimiento'      => 'Mejoría notable en uso autónomo de estrategias',
                'instrumentos'     => 'Escala de bienestar emocional',
                'observaciones'    => 'Familia reporta mejoría en casa también',
                'factores'         => 'Ruido excesivo en recreo',
                'necesidades'      => 'Mayor supervisión en transiciones',
                'recursos'         => 'Auriculares, tarjetas de emoción',
                'coordinacion'     => 'Coordinado con docente jefe',
                'notas'            => 'Revisar en próxima reunión de equipo PIE',
                'created_at'       => now(), 'updated_at' => now(),
            ],
            [
                'fecha'            => '2024-06-15',
                'evaluador'        => 'Jorge Navarro Soto',
                'contexto'         => 'Clase de Matemáticas',
                'emocion'          => 'Frustración moderada',
                'fisica'           => 'Golpear mesa levemente',
                'conductales'      => 'Negativa a continuar la tarea',
                'duracion'         => '15 minutos',
                'inteversion'      => 'Pausa activa y reformulación de la tarea',
                'estrategia'       => 'Dividir la tarea en pasos más pequeños',
                'ayuda'            => 'Docente',
                'ayuda_externa'    => null,
                'corto_plaza'      => 'Adaptar materiales de evaluación',
                'largo_plazo'      => 'Fortalecer tolerancia a la frustración',
                'seguimiento_fecha'=> '2024-07-15',
                'responsable'      => 'Jorge Navarro Soto',
                'seguimiento'      => 'Se observa mayor tolerancia con tareas secuenciadas',
                'instrumentos'     => 'Registro anecdótico',
                'observaciones'    => 'Responde bien cuando se anticipa el nivel de dificultad',
                'factores'         => 'Tarea de alta demanda cognitiva sin apoyo visual',
                'necesidades'      => 'Material adaptado con apoyo visual',
                'recursos'         => 'Fichas visuales, calculadora',
                'coordinacion'     => 'Coordinado con docente de asignatura',
                'notas'            => null,
                'created_at'       => now(), 'updated_at' => now(),
            ],
            [
                'fecha'            => '2024-07-03',
                'evaluador'        => 'Ana Vargas Muñoz',
                'contexto'         => 'Acto escolar',
                'emocion'          => 'Sobrecarga sensorial',
                'fisica'           => 'Tapado de oídos, balanceo',
                'conductales'      => 'Intento de salida del espacio',
                'duracion'         => '20 minutos',
                'inteversion'      => 'Retiro preventivo antes de peak de estímulos',
                'estrategia'       => 'Anticipar eventos masivos con preparación previa',
                'ayuda'            => 'Asistente de aula',
                'ayuda_externa'    => null,
                'corto_plaza'      => 'Evaluar participación parcial en actos',
                'largo_plazo'      => 'Trabajo gradual de tolerancia a estímulos',
                'seguimiento_fecha'=> '2024-08-03',
                'responsable'      => 'Ana Vargas Muñoz',
                'seguimiento'      => 'Familia acepta participación parcial en eventos',
                'instrumentos'     => 'Perfil sensorial',
                'observaciones'    => 'Requiere preparación con 1 semana de anticipación',
                'factores'         => 'Hipersensibilidad auditiva',
                'necesidades'      => 'Anticipación, auriculares, plan de escape',
                'recursos'         => 'Auriculares, tarjeta de salida autorizada',
                'coordinacion'     => 'Dirección del establecimiento',
                'notas'            => 'Incluir en protocolo de actos escolares',
                'created_at'       => now(), 'updated_at' => now(),
            ],
            [
                'fecha'            => '2024-08-19',
                'evaluador'        => 'María González Pizarro',
                'contexto'         => 'Taller de habilidades sociales',
                'emocion'          => 'Ansiedad leve inicial, reducida al avanzar la sesión',
                'fisica'           => 'Sin manifestaciones físicas relevantes',
                'conductales'      => 'Logró participar en actividad de turnos',
                'duracion'         => '45 minutos',
                'inteversion'      => 'Refuerzo positivo y modelado social',
                'estrategia'       => 'Estructurar turnos con señal visual',
                'ayuda'            => null,
                'ayuda_externa'    => null,
                'corto_plaza'      => 'Generalizar habilidades al aula regular',
                'largo_plazo'      => 'Participación autónoma en dinámicas grupales',
                'seguimiento_fecha'=> '2024-09-19',
                'responsable'      => 'María González Pizarro',
                'seguimiento'      => 'Pendiente',
                'instrumentos'     => 'Lista de cotejo de habilidades sociales',
                'observaciones'    => 'Gran avance en contacto visual y espera de turno',
                'factores'         => null,
                'necesidades'      => 'Continuidad del taller',
                'recursos'         => 'Material lúdico estructurado',
                'coordinacion'     => 'Equipo PIE',
                'notas'            => null,
                'created_at'       => now(), 'updated_at' => now(),
            ],
        ]);
    }
}
